[pytest]
addopts = -p no:cacheprovider -W ignore::SyntaxWarning
testpaths = tests
norecursedirs = .pytest_cache __pycache__ pytest-cache-files-* *.egg-info
filterwarnings =
    ignore:websockets\.legacy is deprecated.*:DeprecationWarning
    ignore:'return' in a 'finally' block:SyntaxWarning
